language: node_js
node_js:
- "12"
env:
  global:
  - NPM_TAG=latest
  - RELEASE_VERSION="0.1.0-prerelease.$(date +'%Y%m%d%H%M%S')"
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_deploy:
- npm --no-git-tag-version version $RELEASE_VERSION
deploy:
- provider: npm
  on:
    branch:
    - main
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  tag: $NPM_TAG
